/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing GetCustomerEventsByAccountKeySearchParameterParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCustomerEventsByAccountKeySearchParameterParameterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCustomerEventsByAccountKeySearchParameterParameter
        //private GetCustomerEventsByAccountKeySearchParameterParameter instance;

        public GetCustomerEventsByAccountKeySearchParameterParameterTests()
        {
            // TODO uncomment below to create an instance of GetCustomerEventsByAccountKeySearchParameterParameter
            //instance = new GetCustomerEventsByAccountKeySearchParameterParameter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCustomerEventsByAccountKeySearchParameterParameter
        /// </summary>
        [Fact]
        public void GetCustomerEventsByAccountKeySearchParameterParameterInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCustomerEventsByAccountKeySearchParameterParameter
            //Assert.IsType<GetCustomerEventsByAccountKeySearchParameterParameter>(instance);
        }


        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
