/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * OpenAPI spec version: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OrderBy : IEquatable<OrderBy>
    { 
        /// <summary>
        /// Gets or Sets Attribute
        /// </summary>

        [DataMember(Name="attribute")]
        public string Attribute { get; set; }

        /// <summary>
        /// Gets or Sets LastValue
        /// </summary>

        [DataMember(Name="lastValue")]
        public string LastValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderBy {\n");
            sb.Append("  Attribute: ").Append(Attribute).Append("\n");
            sb.Append("  LastValue: ").Append(LastValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderBy)obj);
        }

        /// <summary>
        /// Returns true if OrderBy instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderBy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderBy other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Attribute == other.Attribute ||
                    Attribute != null &&
                    Attribute.Equals(other.Attribute)
                ) && 
                (
                    LastValue == other.LastValue ||
                    LastValue != null &&
                    LastValue.Equals(other.LastValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Attribute != null)
                    hashCode = hashCode * 59 + Attribute.GetHashCode();
                    if (LastValue != null)
                    hashCode = hashCode * 59 + LastValue.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OrderBy left, OrderBy right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderBy left, OrderBy right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
